### ISSUE TITLE
Modify the results structure and include the detailed table

### ISSUE THREAD

**Issue by blasferna** [blasferna/web-scraping#1]
The current code select the next table and return a `dict`

![image](https://user-images.githubusercontent.com/8385910/109239329-f77dcc00-77b3-11eb-8bdb-796cb3748235.png)

Current `dict` structure

```python
{
    u"Tipo Aseg.": u"TITULAR",
    u"Beneficiarios Activos": u"0",
    u"Nombres": u"JUAN",
    u"Fecha Nacim": u"03-11-1997",
    u"Sexo": u"MASCULINO",
    u"Apellidos": u"LOPEZ",
    u"Elegir": u"",
    u"Nro Documento": u"1234567",
    u"Enrolado": u"NO",
    u"Vencimiento de fe de vida": u"",
}
```
The goal is add the next block in the result `dict`  "Patronales" and the current structure move to "Titular". This table can have one or more records

![image](https://user-images.githubusercontent.com/8385910/109240047-817a6480-77b5-11eb-9bfe-530df6f46ab3.png)

Structure expected.

```json
{
	"Titular": {},
	"Patronales": [
		{},
		{}
	]
}
```

**Comment by ghost** [comment]
i am very new and i am also from non cs biochem engineering can you please help me, how can i modify the result structure. it would be a great help

**Comment by blasferna** [comment]
@Ktmenduro690 I improved the description.
